In [1]:
import sys
sys.path.append("../src")

from fpl.extras.datasets.lp_dataset import PydanticDataset
import pandas as pd

In [2]:
dataset = PydanticDataset(filepath="../data/optimization/lp_data.json")
lp_data = dataset.load()
lp_data

LpData(merged_data=       web_name                    full_name             team  element_type  \
351     Haaland               Erling Haaland  Manchester City             4
328     M.Salah                Mohamed Salah        Liverpool             3
327   Luis Díaz                    Luis Díaz        Liverpool             3
503         Son                Son Heung-min        Tottenham             3
350    Gvardiol               Joško Gvardiol  Manchester City             2
..          ...                          ...              ...           ...
229      Maupay                  Neal Maupay          Everton             4
227  J.Virginia          João Neves Virgínia          Everton             1
225     Holgate                Mason Holgate          Everton             2
223      Garner                 James Garner          Everton             3
655       Forbs  Carlos Roberto Forbs Borges           Wolves             3

    position  now_cost  chance_of_playing_next_round  cost_change_start  \
351      FWD       153                         100.0                  3
328      MID       128                           NaN                  3
327      MID        79                           NaN                  4
503      MID       100                           NaN                  0
350      DEF        60                           NaN                  0
..       ...       ...                           ...                ...
229      FWD        49                           0.0                 -1
227      GKP        40                           NaN                  0
225      DEF        40                           0.0                  0
223      MID        50                         100.0                  0
655      MID        55                           NaN                  0

     pred_pts_6  pred_pts_7  pred_pts_8  pred_pts_9  sell_price  bought_price  \
351    6.438665    5.826997    5.407453    5.765538         153           NaN
328    4.801929    3.849760    3.878346    3.537084         126         125.0
327    5.068843    3.571940    2.951361    2.727838          79           NaN
503    4.417316    3.038105    3.611620    3.237919         100           NaN
350    3.093925    3.760408    3.220076    3.786898          60          60.0
..          ...         ...         ...         ...         ...           ...
229    0.000000    0.000000    0.000000    0.000000          49           NaN
227    0.000000    0.000000    0.000000    0.000000          40           NaN
225    0.000000    0.000000    0.000000    0.000000          40           NaN
223    0.000000    0.000000    0.000000    0.000000          50           NaN
655    0.000000    0.000000    0.000000    0.000000          55           NaN

      total_ev
351  23.438653
328  16.067119
327  14.319982
503  14.304960
350  13.861307
..         ...
229   0.000000
227   0.000000
225   0.000000
223   0.000000
655   0.000000

[661 rows x 15 columns], team_data=    code  draw  form  loss             name  played  points  position  \
1      3     0  None     0          Arsenal       0       0         0
2      7     0  None     0      Aston Villa       0       0         0
3     91     0  None     0      Bournemouth       0       0         0
4     94     0  None     0        Brentford       0       0         0
5     36     0  None     0         Brighton       0       0         0
6      8     0  None     0          Chelsea       0       0         0
7     31     0  None     0   Crystal Palace       0       0         0
8     11     0  None     0          Everton       0       0         0
9     54     0  None     0           Fulham       0       0         0
10    40     0  None     0     Ipswich Town       0       0         0
11    13     0  None     0   Leicester City       0       0         0
12    14     0  None     0        Liverpool       0       0         0
13    43     0  None     0  Manchester City       0       0         0
14     1     0  None     0   Manchester Utd       0       0         0
15     4     0  None     0    Newcastle Utd       0       0         0
16    17     0  None     0  Nott'ham Forest       0       0         0
17    20     0  None     0      Southampton       0       0         0
18     6     0  None     0        Tottenham       0       0         0
19    21     0  None     0         West Ham       0       0         0
20    39     0  None     0           Wolves       0       0         0

   short_name  strength team_division  unavailable  win  \
1         ARS         5          None        False    0
2         AVL         3          None        False    0
3         BOU         3          None        False    0
4         BRE         3          None        False    0
5         BHA         3          None        False    0
6         CHE         3          None        False    0
7         CRY         3          None        False    0
8         EVE         3          None        False    0
9         FUL         3          None        False    0
10        IPS         2          None        False    0
11        LEI         2          None        False    0
12        LIV         4          None        False    0
13        MCI         5          None        False    0
14        MUN         3          None        False    0
15        NEW         4          None        False    0
16        NFO         3          None        False    0
17        SOU         2          None        False    0
18        TOT         3          None        False    0
19        WHU         3          None        False    0
20        WOL         3          None        False    0

    strength_overall_home  strength_overall_away  strength_attack_home  \
1                    1350                   1380                  1370
2                    1120                   1245                  1110
3                    1100                   1100                  1075
4                    1100                   1100                  1105
5                    1100                   1100                  1100
6                    1130                   1255                  1090
7                    1100                   1165                  1110
8                    1090                   1125                  1100
9                    1080                   1125                  1070
10                   1050                   1050                  1050
11                   1050                   1060                  1060
12                   1235                   1370                  1170
13                   1355                   1380                  1335
14                   1115                   1175                  1110
15                   1130                   1285                  1100
16                   1090                   1100                  1085
17                   1050                   1050                  1050
18                   1165                   1225                  1100
19                   1095                   1100                  1060
20                   1095                   1100                  1075

    strength_attack_away  strength_defence_home  strength_defence_away  \
1                   1370                   1330                   1390
2                   1140                   1130                   1350
3                   1100                   1130                   1105
4                   1095                   1100                   1110
5                   1105                   1100                   1100
6                   1180                   1170                   1330
7                   1180                   1090                   1155
8                   1175                   1080                   1080
9                   1130                   1090                   1120
10                  1050                   1050                   1050
11                  1050                   1060                   1050
12                  1350                   1300                   1390
13                  1370                   1375                   1390
14                  1120                   1120                   1230
15                  1185                   1160                   1380
16                  1115                   1090                   1090
17                  1050                   1050                   1050
18                  1125                   1230                   1330
19                  1100                   1130                   1105
20                  1105                   1115                   1100

    pulse_id
1          1
2          2
3        127
4        130
5        131
6          4
7          6
8          7
9         34
10         8
11        26
12        10
13        11
14        12
15        23
16        15
17        20
18        21
19        25
20        38  , type_data=   plural_name plural_name_short singular_name singular_name_short  \
1  Goalkeepers               GKP    Goalkeeper                 GKP
2    Defenders               DEF      Defender                 DEF
3  Midfielders               MID    Midfielder                 MID
4     Forwards               FWD       Forward                 FWD

   squad_select squad_min_select squad_max_select  squad_min_play  \
1             2             None             None               1
2             5             None             None               3
3             5             None             None               2
4             3             None             None               1

   squad_max_play  ui_shirt_specific sub_positions_locked  element_count
1               1               True                 [12]             70
2               5              False                   []            215
3               5              False                   []            303
4               3              False                   []             73  , gameweeks=[6, 7, 8, 9], initial_squad=[347, 335, 211, 350, 339, 342, 328, 199, 4, 207, 148, 414, 13, 277, 408], team_name="It's Coming Home", in_the_bank=2.8, free_transfers=1, current_season='2024-2025', chips_usage={'wildcard1': 6, 'wildcard2': 29, 'free_hit': 11, 'triple_captain': 28, 'bench_boost': None}, forced_transfers={'in': [], 'out': [], 'keep': []})

In [6]:
lp_data.merged_data.query("full_name=='Danny Welbeck'")

,web_name,full_name,team,element_type,position,now_cost,chance_of_playing_next_round,cost_change_start,pred_pts_6,pred_pts_7,pred_pts_8,pred_pts_9,sell_price,bought_price,total_ev
148,Welbeck,Danny Welbeck,Brighton,4,FWD,58,NaN,3,2.79149,2.429906,2.261991,2.731778,56,55.0,10.215164

In [17]:
pd.set_option('display.max_rows', None)

merged_data = lp_data.merged_data
# merged_data.query("web_name == 'Quansah'")
merged_data.query("position == 'GKP'")

,web_name,full_name,team,element_type,position,now_cost,chance_of_playing_next_round,cost_change_start,pred_pts_4,pred_pts_5,pred_pts_6,pred_pts_7,sell_price,bought_price,total_ev
347,Ederson M.,Ederson Santana de Moraes,Manchester City,1,GKP,55,NaN,0,2.844473,3.095599,2.582975,3.209785,55,NaN,11.732832
310,A.Becker,Alisson Ramses Becker,Liverpool,1,GKP,55,NaN,0,2.734161,2.971716,2.966772,3.055421,55,NaN,11.728070
15,Raya,David Raya Martin,Arsenal,1,GKP,55,NaN,0,2.076997,1.620918,3.232540,3.535590,55,NaN,10.466044
47,Martinez,Emiliano Martínez Romero,Aston Villa,1,GKP,50,NaN,0,2.658412,2.182278,2.204007,2.165702,50,NaN,9.210399
152,Arrizabalaga,Kepa Arrizabalaga,Bournemouth,1,GKP,45,NaN,0,1.831271,1.513474,3.096761,2.582015,45,NaN,9.023521
185,Sánchez,Robert Sánchez,Chelsea,1,GKP,45,NaN,0,2.224628,2.432710,2.080657,2.222427,45,NaN,8.960422
235,Pickford,Jordan Pickford,Everton,1,GKP,49,NaN,-1,1.964346,2.173811,2.439039,2.038653,49,NaN,8.615850
146,Verbruggen,Bart Verbruggen,Brighton,1,GKP,45,100.0,0,2.343721,2.466154,1.676480,1.859307,45,NaN,8.345662
201,Henderson,Dean Henderson,Crystal Palace,1,GKP,45,NaN,0,2.153228,2.263543,2.261932,1.629174,45,NaN,8.307877
508,Vicario,Guglielmo Vicario,Tottenham,1,GKP,50,NaN,0,1.906688,2.260554,1.948653,2.015751,50,NaN,8.131646
413,Pope,Nick Pope,Newcastle Utd,1,GKP,50,NaN,0,2.044034,2.160914,1.685752,2.219948,50,NaN,8.110648
91,Flekken,Mark Flekken,Brentford,1,GKP,45,NaN,0,1.536170,1.849120,2.471235,2.230502,45,NaN,8.087026
248,Leno,Bernd Leno,Fulham,1,GKP,50,NaN,0,2.412613,2.030185,2.172866,1.423972,50,NaN,8.039636
293,Hermansen,Mads Hermansen,Leicester City,1,GKP,45,NaN,0,1.879136,2.224802,1.413728,2.306856,45,NaN,7.824522
443,Sels,Matz Sels,Nott'ham Forest,1,GKP,45,NaN,0,1.558693,1.927463,2.506556,1.808788,45,NaN,7.801500
204,Johnstone,Sam Johnstone,Wolves,1,GKP,44,NaN,-1,2.193960,1.959611,1.725883,1.918355,44,NaN,7.797809
383,Onana,André Onana,Manchester Utd,1,GKP,50,NaN,0,2.095518,1.917067,1.948409,1.744512,50,NaN,7.705506
568,Muric,Arijanet Muric,Ipswich Town,1,GKP,44,100.0,-1,1.774815,2.068904,1.933709,1.845713,44,NaN,7.623140
14,Ramsdale,Aaron Ramsdale,Southampton,1,GKP,44,NaN,-1,2.006266,2.153301,1.845689,1.453703,44,NaN,7.458959
513,Areola,Alphonse Areola,West Ham,1,GKP,45,75.0,0,1.651430,1.433776,1.494099,1.703600,45,NaN,6.282905
556,King,Tom King,Wolves,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
358,Ortega Moreno,Stefan Ortega Moreno,Manchester City,1,GKP,54,NaN,-1,0.000000,0.000000,0.000000,0.000000,54,NaN,0.000000
396,Dúbravka,Martin Dúbravka,Newcastle Utd,1,GKP,44,100.0,-1,0.000000,0.000000,0.000000,0.000000,44,NaN,0.000000
374,Heaton,Tom Heaton,Manchester Utd,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
510,Whiteman,Alfie Whiteman,Tottenham,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
367,Bayindir,Altay Bayindir,Manchester Utd,1,GKP,44,NaN,-1,0.000000,0.000000,0.000000,0.000000,44,NaN,0.000000
554,José Sá,José Malheiro de Sá,Wolves,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,45.0,0.000000
454,Bazunu,Gavin Bazunu,Southampton,1,GKP,44,0.0,-1,0.000000,0.000000,0.000000,0.000000,44,NaN,0.000000
488,Forster,Fraser Forster,Tottenham,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
521,Fabianski,Łukasz Fabiański,West Ham,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
465,Lis,Mateusz Lis,Southampton,1,GKP,40,0.0,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
479,Austin,Brandon Austin,Tottenham,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
466,Lumley,Joe Lumley,Southampton,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
469,McCarthy,Alex McCarthy,Southampton,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
414,Ruddy,John Ruddy,Newcastle Utd,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,40.0,0.000000
412,Odysseas,Odysseas Vlachodimos,Newcastle Utd,1,GKP,44,NaN,-1,0.000000,0.000000,0.000000,0.000000,44,NaN,0.000000
427,C.Miguel,Carlos Miguel dos Santos Pereira,Nott'ham Forest,1,GKP,44,NaN,-1,0.000000,0.000000,0.000000,0.000000,44,NaN,0.000000
536,Bentley,Daniel Bentley,Wolves,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
522,Foderingham,Wes Foderingham,West Ham,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
109,Valdimarsson,Hákon Valdimarsson,Brentford,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
142,Steele,Jason Steele,Brighton,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
344,Carson,Scott Carson,Manchester City,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
155,Bettinelli,Marcus Bettinelli,Chelsea,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
154,Bergström,Lucas Bergström,Chelsea,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
615,Rushworth,Carl Rushworth,Brighton,1,GKP,40,0.0,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
639,Setford,Tommy Setford,Arsenal,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
39,Gauci,Joe Gauci,Aston Villa,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
73,Neto,Norberto Murara Neto,Arsenal,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
5,Hein,Karl Hein,Arsenal,1,GKP,40,0.0,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
46,Marschall,Filip Marschall,Aston Villa,1,GKP,40,0.0,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
51,Olsen,Robin Olsen,Aston Villa,1,GKP,45,100.0,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
599,Dennis,Will Dennis,Bournemouth,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
84,Travers,Mark Travers,Bournemouth,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
75,Paulsen,Alex Paulsen,Bournemouth,1,GKP,40,0.0,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
641,Zych,Oliwier Zych,Aston Villa,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
55,Sinisalo,Viljami Sinisalo,Aston Villa,1,GKP,40,0.0,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
183,Petrović,Đorđe Petrović,Chelsea,1,GKP,44,0.0,-1,0.000000,0.000000,0.000000,0.000000,44,NaN,0.000000
294,Iversen,Daniel Iversen,Leicester City,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
283,Walton,Christian Walton,Ipswich Town,1,GKP,45,NaN,0,0.000000,0.000000,0.000000,0.000000,45,NaN,0.000000
280,Slicker,Cieran Slicker,Ipswich Town,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
325,Kelleher,Caoimhin Kelleher,Liverpool,1,GKP,44,NaN,-1,0.000000,0.000000,0.000000,0.000000,44,NaN,0.000000
308,Ward,Danny Ward,Leicester City,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
304,Stolarczyk,Jakub Stolarczyk,Leicester City,1,GKP,40,0.0,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
445,Turner,Matt Turner,Crystal Palace,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
209,Matthews,Remi Matthews,Crystal Palace,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
581,Jørgensen,Filip Jørgensen,Chelsea,1,GKP,44,NaN,-1,0.000000,0.000000,0.000000,0.000000,44,NaN,0.000000
227,J.Virginia,João Neves Virgínia,Everton,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
242,Benda,Steven Benda,Fulham,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000
624,Begovic,Asmir Begovic,Everton,1,GKP,40,NaN,0,0.000000,0.000000,0.000000,0.000000,40,NaN,0.000000